import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Notebook } from "lucide-react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <header className="bg-blue-600 p-4 ">
          <a
            href=""
            className="logo flex gap-2 text-gray-200 font-bold text-2xl pl-20"
          >
            <Notebook width={29} height={29} />
            KanbanBoard
          </a>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
